/**
 * Bible Book Aliases
 * Maps canonical book names to common spoken variations and AI mishearings
 * Covers all 66 books of the Bible with extensive speech-to-text variations
 */

/* ---------- SHARED BASE ALIASES ---------- */
// For books with numbered versions (1 Samuel, 2 Samuel, etc.)
// Add aliases here once, they apply to all numbered versions

const SAMUEL_ALIASES = [
  "samuel",
  "sam",
  "samual",
  "sam-u-well",
  "some well",
  "sam-u-l",
  "a mule",
];
const KINGS_ALIASES = ["kings", "king", "kinks", "keens", "things", "king's"];
const CHRONICLES_ALIASES = [
  "chronicles",
  "chronicle",
  "cronicles",
  "chronics",
  "chronic-kills",
  "cron-ick-les",
  "kron-ick-ulls",
  "comical",
];
const CORINTHIANS_ALIASES = [
  "corinthians",
  "corinthian",
  "corenthians",
  "core-in-the-ends",
  "curtain-the-ends",
  "current-the-ins",
  "corinth-ends",
  "cor-in-thee-ans",
  "grin-the-ends",
];
const THESSALONIANS_ALIASES = [
  "thessalonians",
  "thessalonian",
  "thesalonians",
  "thessel-on-the-ends",
  "thessel-own-yans",
  "fessel-on-ians",
  "thess-a-low-nee-ans",
  "vessel-on-ians",
  "thistle-on-ians",
  "thes-alone-yans",
];
const TIMOTHY_ALIASES = [
  "timothy",
  "tim",
  "timothee",
  "tim-o-thee",
  "tim-a-thy",
  "timmy-thee",
  "tim-o-thy",
  "timmy-thy",
  "tim-u-thy",
  "tim-mathy",
];
const PETER_ALIASES = [
  "peter",
  "peta",
  "pieter",
  "pee-ter",
  "pee-tar",
  "pee-tor",
  "petar",
  "peater",
];
const JOHN_ALIASES = [
  "john",
  "jon",
  "jawn",
  "jhon",
  "jahn",
  "joan",
  "gian",
  "j-o-n",
];

/* ---------- HELPER FUNCTION ---------- */
// Generates numbered book aliases from base aliases
function numberedAliases(num: 1 | 2 | 3, baseAliases: string[]): string[] {
  const prefixes = {
    1: ["1", "first", "1st", "one", "won", "once", "on"],
    2: ["2", "second", "2nd", "two", "too", "to", "tu"],
    3: ["3", "third", "3rd", "three", "tree", "thru"],
  };

  const result: string[] = [];
  for (const prefix of prefixes[num]) {
    for (const base of baseAliases) {
      result.push(`${prefix} ${base}`);
      result.push(`${base} ${prefix.replace(/\D/g, "") || num}`); // "samuel 1"
    }
  }
  return result;
}

/* ---------- BOOK ALIASES ---------- */

export const BOOK_ALIASES: Record<string, string[]> = {
  // ========== OLD TESTAMENT ==========

  // Pentateuch
  Genesis: [
    "genesis",
    "jenesis",
    "genes is",
    "gen",
    "genetics",
    "jeanette's",
    "jen is cis",
    "gen-sys",
    "guinness",
    "gen-z",
    "gems is",
    "jettison",
    "jen's sis",
    "gen assist",
  ],
  Exodus: [
    "exodus",
    "eksodus",
    "ex o dus",
    "exodas",
    "exo",
    "exit us",
    "extra us",
    "egg zest",
    "exists",
    "exodos",
    "hexed us",
    "axe dusk",
    "echo dust",
    "x-dust",
    "exit bus",
  ],
  Leviticus: [
    "leviticus",
    "levi ticus",
    "levitikus",
    "lev",
    "level tick us",
    "love it kiss",
    "leave it to us",
    "live it i guess",
    "leveling us",
    "live hit kiss",
    "love ethics",
    "left it cuz",
    "levity kiss",
    "level tics",
  ],
  Numbers: [
    "numbers",
    "numbas",
    "numba",
    "num",
    "number",
    "slumber",
    "num-bears",
    "no bears",
    "new birds",
    "nomads",
    "nimrod",
    "numb-er",
    "neighbors",
    "num-verse",
  ],
  Deuteronomy: [
    "deuteronomy",
    "deutronomy",
    "doot eronomy",
    "deut",
    "deutronomain",
    "do tour on me",
    "due to ron on me",
    "duty on me",
    "do-it-on-me",
    "deter-on-me",
    "due to economy",
    "do run on me",
    "two to run on me",
    "dew on me",
    "dude run on me",
    "de-train-on-me",
  ],

  // Historical Books
  Joshua: [
    "joshua",
    "josh",
    "joshuah",
    "josh you are",
    "josh away",
    "josh wah",
    "jaw shoe a",
    "joss you a",
    "just you a",
    "josh who a",
    "josh-ua",
    "gosh you are",
    "josh-wa",
    "gosh-u-a",
  ],
  Judges: [
    "judges",
    "jud ges",
    "judged",
    "judicious",
    "j-edges",
    "jud-gees",
    "just us",
    "grudges",
    "drudges",
    "g-edges",
    "judge's",
    "jud-gets",
    "jud-jays",
  ],
  Ruth: [
    "ruth",
    "root",
    "rooth",
    "route",
    "roof",
    "youth",
    "truth",
    "ruthless",
    "rue",
    "booth",
    "wreaths",
    "rude",
    "roo",
  ],
  "1 Samuel": numberedAliases(1, SAMUEL_ALIASES),
  "2 Samuel": numberedAliases(2, SAMUEL_ALIASES),
  "1 Kings": numberedAliases(1, KINGS_ALIASES),
  "2 Kings": numberedAliases(2, KINGS_ALIASES),
  "1 Chronicles": numberedAliases(1, CHRONICLES_ALIASES),
  "2 Chronicles": numberedAliases(2, CHRONICLES_ALIASES),
  Ezra: [
    "ezra",
    "ez ra",
    "ezrah",
    "esra",
    "extra",
    "azra",
    "ez-rah",
    "israel",
    "ez-raw",
    "s-rah",
    "e-z-raw",
  ],
  Nehemiah: [
    "nehemiah",
    "nehamiah",
    "neheamiah",
    "neh",
    "knee high maya",
    "knee hem i-ah",
    "nay-uh-maya",
    "near my uh",
    "neo-maya",
    "near maya",
    "knee-am-i-ah",
    "name-i-ah",
    "knee-high-my-ah",
    "knee-him-i-ah",
    "nay-him-eye-uh",
  ],
  Esther: [
    "esther",
    "esta",
    "ester",
    "astor",
    "aster",
    "extra",
    "s-ter",
    "est-her",
    "hester",
    "easter",
    "as-ter",
    "ess-ter",
  ],

  // Wisdom / Poetry
  Job: [
    "job",
    "jobe",
    "joab",
    "jo-be",
    "joe-be",
    "g-o-b",
    "j-o-b",
    "jaw-b",
    "jow-b",
  ],
  Psalms: [
    "psalm",
    "psalms",
    "salms",
    "sams",
    "psa",
    "palms",
    "sam's",
    "songs",
    "slams",
    "sums",
    "p-salms",
    "sahms",
    "sah-mms",
    "somms",
  ],
  Proverbs: [
    "proverbs",
    "pro verbs",
    "proverb",
    "prov",
    "pro-verb",
    "per-verbs",
    "pro-verse",
    "prob-verbs",
    "proper-verbs",
    "pro-vurbs",
    "pro-b-urbs",
    "pru-verbs",
  ],
  Ecclesiastes: [
    "ecclesiastes",
    "eclesiastes",
    "ecclesisastes",
    "eccl",
    "a-classy-as-tease",
    "e-classy-as-tease",
    "egg-clase-e-as-tees",
    "ec-cle-si-as-tease",
    "e-cleez-e-as-tees",
    "a-cleez-e-as-tees",
    "ec-cleez-ee-as-tease",
  ],
  "Song of Solomon": [
    "song of solomon",
    "song of songs",
    "songs of solomon",
    "songs of songs",
    "solomon song",
    "song of salmon",
    "song of solemn",
    "song of sol-o-man",
    "song of soul-man",
    "song of soul-a-man",
    "song of sol-low-man",
    "song of solo-man",
  ],

  // Major Prophets
  Isaiah: [
    "isaiah",
    "isaya",
    "isayah",
    "isa",
    "i say ah",
    "i-zay-ah",
    "eyes-zay-ah",
    "i-say-uh",
    "is-eye-ah",
    "is-a-ah",
    "i-zaya",
    "eyes-eye-uh",
    "i-z-ah",
  ],
  Jeremiah: [
    "jeremiah",
    "jeremiya",
    "jeremaiah",
    "jer",
    "jerry-maya",
    "jeremy-ah",
    "chair-a-maya",
    "jerry-my-ah",
    "geri-maya",
    "jerry-mi-ah",
    "jer-a-maya",
    "jerry-mine-ah",
    "jer-e-mi-ah",
    "jery-maya",
    "jerry-miah",
  ],
  Lamentations: [
    "lamentations",
    "lamentation",
    "lam",
    "lemon-stations",
    "lamb-in-stations",
    "lament-stations",
    "lemon-tastes",
    "lamb-en-tations",
    "lament-nations",
    "lemon-nations",
    "lam-en-tations",
    "lamb-on-stations",
    "lemon-tations",
  ],
  Ezekiel: [
    "ezekiel",
    "ezikel",
    "ezekial",
    "ezek",
    "easy-kill",
    "e-zee-kill",
    "e-zeek-e-ul",
    "easy-key-ul",
    "e-seek-e-ul",
    "e-zeek-e-el",
    "e-zeek-ee-ul",
    "easy-kiel",
    "easy-keel",
    "e-zeek-yul",
  ],
  Daniel: [
    "daniel",
    "danyel",
    "dan",
    "dan-yul",
    "dan-u-el",
    "dan-i-el",
    "dan-yal",
    "dan-i-ell",
    "dan-yell",
    "denny-ul",
    "danny-ul",
    "dan-y-el",
    "dan-yo",
    "dan-i-al",
  ],

  // Minor Prophets
  Hosea: [
    "hosea",
    "hozea",
    "hoseah",
    "who say ah",
    "ho-say-ah",
    "hose-a",
    "who sayer",
    "o-say-ah",
    "jose",
    "hose-uh",
    "who's sayer",
    "whose-a",
    "ho-see-ah",
    "who-zaya",
  ],
  Joel: [
    "joel",
    "jo el",
    "jo-el",
    "jewel",
    "joul",
    "joule",
    "joy-el",
    "joe-l",
    "j-well",
    "jol",
    "joe-well",
    "jowell",
  ],
  Amos: [
    "amos",
    "aimos",
    "aim-us",
    "famous",
    "a-mouse",
    "aim-os",
    "amy's",
    "a-most",
    "hay-mos",
    "aim-is",
    "a-moss",
    "am-oss",
  ],
  Obadiah: [
    "obadiah",
    "obadaya",
    "obediah",
    "over-dye-ah",
    "oh-ba-dye-ah",
    "open-dye-ah",
    "o-bad-eye-uh",
    "over-die-ah",
    "oh-bad-i-ah",
    "o-ba-dia",
    "a-bad-eye-uh",
    "ob-a-dia",
    "over-day-ah",
  ],
  Jonah: [
    "jonah",
    "jona",
    "jonuh",
    "joan of",
    "join-ah",
    "joe-nah",
    "jonas",
    "joan-ah",
    "june-ah",
    "john-ah",
    "jo-na",
    "gona",
    "joan-uh",
    "jaw-na",
  ],
  Micah: [
    "micah",
    "mika",
    "mica",
    "my-kah",
    "mike-ah",
    "maker",
    "my-car",
    "me-kah",
    "mike-a",
    "my-kuh",
    "me-ca",
    "my-ga",
  ],
  Nahum: [
    "nahum",
    "naham",
    "nayhum",
    "nay-hum",
    "name",
    "nay-him",
    "no-hum",
    "nah-um",
    "na-hoom",
    "naim",
    "gnome",
    "nay-em",
    "nah-em",
  ],
  Habakkuk: [
    "habakkuk",
    "habakuk",
    "habakook",
    "have a cook",
    "habba-cook",
    "have a cup",
    "how back cook",
    "ha-back-uk",
    "have-a-look",
    "hab-a-cook",
    "hub-a-cook",
    "half-a-cook",
    "ha-ba-kuk",
    "heavy-cook",
  ],
  Zephaniah: [
    "zephaniah",
    "zefaniah",
    "zephenia",
    "zephyr-ny-ah",
    "saph-an-i-ah",
    "stef-an-i-ah",
    "zeph-an-eye-uh",
    "seven-i-ah",
    "zeph-an-i-a",
    "zeff-an-eye-uh",
    "steph-an-eye-uh",
    "zeph-ny-ah",
    "zeph-a-nye",
  ],
  Haggai: [
    "haggai",
    "hagai",
    "hagye",
    "hag-eye",
    "hag-guy",
    "hay-guy",
    "ha-guy",
    "hag-i",
    "hag-gay",
    "hey-guy",
    "high-guy",
    "hag-a-i",
    "hack-eye",
  ],
  Zechariah: [
    "zechariah",
    "zachariah",
    "zekeriah",
    "zech",
    "zack-a-rye-ah",
    "zucker-eye-ah",
    "zack-a-ri-ah",
    "sec-a-rye-ah",
    "sak-a-rye-ah",
    "zack-i-ah",
    "zach-a-ry-ah",
    "zack-aria",
    "zack-area",
    "zack-a-rye",
  ],
  Malachi: [
    "malachi",
    "malaki",
    "malakai",
    "mal",
    "mal-a-kai",
    "mala-chi",
    "mal-a-key",
    "mala-guy",
    "mal-uh-kai",
    "mal-a-shy",
    "mal-a-chee",
    "mall-a-kai",
    "mal-i-kai",
    "male-a-kai",
    "mal-a-kye",
  ],

  // ========== NEW TESTAMENT ==========

  // Gospels
  Matthew: [
    "matthew",
    "mathew",
    "mat stew",
    "math you",
    "matt",
    "mat",
    "math-hew",
    "math-u",
    "mat-hue",
    "map-hew",
    "math-view",
    "matt-you",
    "mad-hue",
    "mat-shoe",
    "math-yew",
  ],
  Mark: [
    "mark",
    "mak",
    "marc",
    "marque",
    "mask",
    "mart",
    "mock",
    "arc",
    "merk",
    "merc",
    "marx",
  ],
  Luke: [
    "luke",
    "look",
    "luk",
    "luc",
    "luck",
    "lou-k",
    "lewk",
    "l-u-k",
    "loot",
    "lake",
    "luk-e",
  ],
  John: JOHN_ALIASES, // Single John (Gospel)

  // History
  Acts: [
    "acts",
    "act",
    "aks",
    "axe",
    "acts of the apostles",
    "ax",
    "axed",
    "ask",
    "at's",
    "ad's",
    "x",
    "eggs",
    "hacks",
  ],

  // Pauline Epistles
  Romans: [
    "romans",
    "rowmans",
    "roman",
    "rom",
    "roman's",
    "row-mans",
    "roam-ans",
    "rom-ins",
    "row-minns",
    "romaine's",
    "row-mends",
    "roam-ins",
    "ro-mans",
    "row-mance",
  ],
  "1 Corinthians": numberedAliases(1, CORINTHIANS_ALIASES),
  "2 Corinthians": numberedAliases(2, CORINTHIANS_ALIASES),
  Galatians: [
    "galatians",
    "galashians",
    "galations",
    "gal",
    "galactic-shuns",
    "gal-a-shuns",
    "gallery-shuns",
    "goal-a-shuns",
    "gals-a-shuns",
    "gal-lay-shuns",
    "gala-shuns",
    "glaciation",
    "gal-asian",
    "gall-ations",
    "gal-a-tian",
  ],
  Ephesians: [
    "ephesians",
    "efesians",
    "ephesions",
    "eph",
    "e-fish-uns",
    "app-he-shuns",
    "a-fish-ins",
    "eff-he-shuns",
    "e-fees-shuns",
    "e-phee-shuns",
    "a-phee-shuns",
    "efficient",
    "eff-ee-shuns",
    "if-he-shuns",
    "e-fess-shuns",
  ],
  Philippians: [
    "philippians",
    "flipians",
    "philipians",
    "phil",
    "fill-up-pians",
    "philip-peens",
    "fill-it-peens",
    "phil-up-peons",
    "fill-up-ee-ans",
    "flip-peens",
    "philip-ians",
    "flip-ians",
    "phillip-ians",
    "phil-a-peens",
    "phil-a-pians",
  ],
  Colossians: [
    "colossians",
    "colashians",
    "colossions",
    "col",
    "call-o-shuns",
    "coal-o-shuns",
    "collusions",
    "co-loss-ians",
    "call-u-shuns",
    "coal-ush-uns",
    "ca-loss-ians",
    "call-oceans",
    "coal-oceans",
    "co-lush-uns",
  ],
  "1 Thessalonians": numberedAliases(1, THESSALONIANS_ALIASES),
  "2 Thessalonians": numberedAliases(2, THESSALONIANS_ALIASES),
  "1 Timothy": numberedAliases(1, TIMOTHY_ALIASES),
  "2 Timothy": numberedAliases(2, TIMOTHY_ALIASES),
  Titus: [
    "titus",
    "tytus",
    "tite us",
    "tight-us",
    "tie-tuss",
    "tighten-us",
    "tightness",
    "tidus",
    "tight-is",
    "tide-us",
    "tie-tis",
    "tight-est",
    "tie-tubs",
  ],
  Philemon: [
    "philemon",
    "filemon",
    "phylemon",
    "phm",
    "file-a-mon",
    "phil-e-mon",
    "fill-a-mon",
    "file-man",
    "phil-a-mon",
    "file-m-on",
    "fill-a-man",
    "fly-man",
    "phil-e-man",
    "filet-mon",
    "filet-minion",
  ],

  // General Epistles
  Hebrews: [
    "hebrews",
    "hebrew",
    "heb",
    "he-brews",
    "he-bruise",
    "he-brows",
    "hay-brews",
    "he-bruhs",
    "he-breeze",
    "he-brooz",
    "e-brews",
    "hee-brews",
  ],
  James: [
    "james",
    "jams",
    "jaymes",
    "jay-mes",
    "gem-es",
    "gems",
    "games",
    "jaimie's",
    "j-ames",
    "jay-m-z",
    "jane's",
    "jay-miss",
    "j-mes",
  ],
  "1 Peter": numberedAliases(1, PETER_ALIASES),
  "2 Peter": numberedAliases(2, PETER_ALIASES),
  "1 John": numberedAliases(1, JOHN_ALIASES),
  "2 John": numberedAliases(2, JOHN_ALIASES),
  "3 John": numberedAliases(3, JOHN_ALIASES),
  Jude: [
    "jude",
    "jood",
    "jewed",
    "jud",
    "jued",
    "dude",
    "food",
    "rude",
    "j-u-d-e",
    "judah",
    "judged",
    "jude-ah",
  ],

  // Apocalyptic
  Revelation: [
    "revelation",
    "revelations",
    "revolution",
    "rev",
    "apocalypse",
    "rev-a-lay-shun",
    "rev-e-lay-shun",
    "revel-asian",
    "rev-u-lay-shun",
    "reveal-a-shun",
    "rev-e-lotion",
    "rev-e-lation",
    "rev-lay-shun",
    "rebel-asian",
  ],
};

/**
 * Get canonical book name from alias
 */
export function getCanonicalBook(alias: string): string | null {
  const lowerAlias = alias.toLowerCase();

  for (const [canonical, aliases] of Object.entries(BOOK_ALIASES)) {
    if (aliases.includes(lowerAlias)) {
      return canonical;
    }
  }

  return null;
}
